### ISSUE TITLE
PCMS 1.0.22 "Something went wrong installing sharp" when using this plugin

### ISSUE THREAD

**Issue by Etheliene** [invakid404/payload-blurhash-plugin#24]
Hey there, first of great idea, I was just about to to do something like this myself!

Unfortunately with the latest version of Payload CMS I (1.0.22 at writing time) I am unable to use it since there seems to be a conflict with sharp. Please advise or update if possible :)

**Comment by invakid404** [comment]
@Etheliene version 1.0.3 of the plugin appears to install just fine with Yarn and Payload 1.0.22, what exactly is the error you're experiencing?

**Comment by invakid404** [comment]
@Etheliene hey, just checking whether this is still an issue for you, please let me know so that I know whether there's still work to do here :^)

**Comment by Etheliene** [comment]
Hey, thank you for checking in. I do not seem to have that issue anymore  - at the moment -
