### ISSUE TITLE
Add Related GitHub Topics

### ISSUE THREAD

**Issue by denolfe** [invakid404/payload-blurhash-plugin#3]
Hey invakid404, the Payload team is trying to aggregate all of the plugins for payload on this page here: https://github.com/topics/payload-plugin

It would be great if you could add a few topics to your repo to make it show up there: `payload-plugin`, `payload`, and `payloadcms`. This is done by clicking the gear icon on the right side of your repo's main page. Thanks! 👍

**Comment by invakid404** [comment]
@denolfe thanks for reaching out, I've added relevant topics to the repo. I'll keep that in mind for any other plugins I end up making and publishing :^)
