### ISSUE TITLE
TypeError: The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by Etheliene** [invakid404/payload-blurhash-plugin#71]
I am not sure if it's an error on my end, but I receive this error when trying to save an existing image.

My Collection Config:
```typescript
  upload: {
    adminThumbnail: 'card',
    staticDir: 'media',
    mimeTypes: ['image/*', 'application/pdf', 'video/mp4', 'video/Ogg', 'video/WebM'],
    ...
    ],
  },
```

The error appears here:
```typescript
 mediaDir = getMediaDirectory(req.payload, req.collection);
 filepath = path.join(mediaDir, data.filename);
```

**Comment by invakid404** [comment]
@Etheliene a minimal reproducible example would be useful so that I can take a look.

And sorry for the late response -- I'm pretty busy nowadays, but I'll try to make some more time for this project in the upcoming weeks, considering it is getting some traction.

**Comment by invakid404** [comment]
I'd assume no news is good news, feel free to reopen if issue persists.
