### ISSUE TITLE
Add check for mimeType before trying to create the blurhash

### ISSUE THREAD

**Issue by Etheliene** [invakid404/payload-blurhash-plugin#88]
I have stumbled upon the following:

My "media" collection supports PDF / Images and Videos. I have noticed that when the plugin is activated, I can't upload videos (that what has been tested) due to the fact that it seems to try to create a blurshash even though it is not an image file.

Looking into the source code I could not find something like that either (but maybe I am blind).

Could you please provide a check for the mimetype? kindly asking.

**Comment by invakid404** [comment]
Hey @Etheliene, thanks for the issue, this was on my TODO list initially but it seems like I forgot to implement it.

I think it's reasonable to include it as an option in the config and have it act on all "image" MIME types by default and use something like [minimatch](https://www.npmjs.com/package/minimatch) to allow the user to specify a set of patterns to compute blurhashes for.

Does that seem reasonable to you?

**Comment by Etheliene** [comment]
Absolutely! :)

**Comment by invakid404** [comment]
@Etheliene this was implemented in https://github.com/invakid404/payload-blurhash-plugin/commit/dead331fd1ae4baf67c86304883f1978ea82f242

It should be present in `1.2.0` (had to skip a few versions due to previous failed publishes :D), would appreciate your input on it.

**Comment by invakid404** [comment]
Since there have been no further complaints, I'd assume it's working properly nowadays.
