### ISSUE TITLE
Incompatibility with cloud storage plugin

### ISSUE THREAD

**Issue by miguderp** [invakid404/payload-blurhash-plugin#95]
Heya 👋🏻 

Just wanted to notify that this plugin seems incompatible with [`@payloadcms/plugin-cloud-storage`](https://github.com/payloadcms/plugin-cloud-storage) – it breaks it and fails all uploads to S3 (in my case, I haven’t tested with the other providers).

Unless if I set `disableLocalStorage` of the cloud plugin to `false` (which defaults to `true`), I get the following error:

![image](https://user-images.githubusercontent.com/7307687/206519977-7f8952c1-5c38-4528-9bda-ecf95575b33e.png)

Doing so correctly sends the image to my S3 bucket but it also creates a copy locally and keeps the data pointing the latter.

**Comment by invakid404** [comment]
@miguderp yep, I am aware of this, thanks for bringing it to my attention. I haven't experimented with cloud storage for Payload, so I wouldn't know what the best way to approach this would be. I can take a look soon-ish and let you know. If you have any ideas, feel free to share :^)

**Comment by invakid404** [comment]
Implemented in [v1.3.0](https://npmjs.com/payload-blurhash-plugin).

**Comment by matthijs166** [comment]
Oehhh very cool! Think I will add it back into my projects again 🥇
